import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'
import { Providers } from '@/lib/providers'
import ThemeSwitcher from './components/theme/theme-switcher'
import Footer from './components/footer'

const font = Lato({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <Providers>
                    <ThemeSwitcher />
                    <main className={font.className}>{children}</main>
                    <Footer />
                </Providers>
            </body>
        </html>
    )
}
